/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.login.view;

import br.com.ifba.usuario.validar.ValidadorUsuario;
import br.com.ifba.usuario.entity.Usuario;
import java.awt.Color;
import java.time.LocalDateTime;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import java.util.Arrays;

/**
 *
 * @author guest
 */
public class TelaCadastro extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCadastro.class.getName());

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblCpf = new javax.swing.JLabel();
        txtCpf = new javax.swing.JTextField();
        lblGenero = new javax.swing.JLabel();
        txtNascimento = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        txtLogin = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        txtConfirmarSenha = new javax.swing.JPasswordField();
        lblNascimento = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        lblConfirmarSenha = new javax.swing.JLabel();
        boxGenero = new javax.swing.JComboBox<>();
        boxCargo = new javax.swing.JComboBox<>();
        btnCriarConta = new javax.swing.JButton();
        txtNomeErro = new javax.swing.JLabel();
        txtCpfErro = new javax.swing.JLabel();
        txtNascimentoErro = new javax.swing.JLabel();
        txtTelefoneErro = new javax.swing.JLabel();
        txtLoginErro = new javax.swing.JLabel();
        txtSenhaErro = new javax.swing.JLabel();
        txtConfirmaSenhaErro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNome.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblNome.setText("Nome Completo");

        txtNome.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N

        lblCpf.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblCpf.setText("CPF");

        txtCpf.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        txtCpf.addActionListener(this::txtCpfActionPerformed);

        lblGenero.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblGenero.setText("Genero");

        txtNascimento.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N

        txtTelefone.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N

        txtLogin.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N

        txtSenha.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N

        txtConfirmarSenha.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N

        lblNascimento.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblNascimento.setText("Data de Nascimento");

        lblTelefone.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblTelefone.setText("Telefone");

        lblCargo.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblCargo.setText("Cargo");

        lblLogin.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblLogin.setText("Login");

        lblSenha.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblSenha.setText("Senha");

        lblConfirmarSenha.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblConfirmarSenha.setText("Confirmar Senha");

        boxGenero.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        boxGenero.setMaximumRowCount(2);
        boxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));
        boxGenero.addActionListener(this::boxGeneroActionPerformed);

        boxCargo.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        boxCargo.setMaximumRowCount(3);
        boxCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerente", "Estoquista", "Repositor" }));

        btnCriarConta.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btnCriarConta.setText("Criar Conta");
        btnCriarConta.addActionListener(this::btnCriarContaActionPerformed);

        txtNomeErro.setForeground(new java.awt.Color(255, 0, 0));

        txtCpfErro.setForeground(new java.awt.Color(255, 0, 0));

        txtNascimentoErro.setForeground(new java.awt.Color(255, 0, 0));

        txtTelefoneErro.setForeground(new java.awt.Color(255, 0, 0));

        txtLoginErro.setForeground(new java.awt.Color(255, 0, 0));

        txtSenhaErro.setForeground(new java.awt.Color(255, 0, 0));

        txtConfirmaSenhaErro.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblGenero)
                            .addComponent(lblCpf)
                            .addComponent(lblNome)
                            .addComponent(lblNascimento)
                            .addComponent(lblTelefone)
                            .addComponent(lblCargo)
                            .addComponent(lblLogin)
                            .addComponent(lblSenha)
                            .addComponent(lblConfirmarSenha))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtConfirmaSenhaErro))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtSenhaErro))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtLoginErro))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtTelefoneErro))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(318, 318, 318)
                                .addComponent(txtNascimentoErro))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtNomeErro))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCpfErro))
                            .addComponent(boxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addComponent(btnCriarConta)))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeErro))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpf)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCpfErro))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGenero)
                    .addComponent(boxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNascimentoErro)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNascimento)
                        .addComponent(txtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefone)
                    .addComponent(txtTelefoneErro))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCargo)
                    .addComponent(boxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLogin)
                    .addComponent(txtLoginErro))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSenha)
                    .addComponent(txtSenhaErro))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblConfirmarSenha)
                    .addComponent(txtConfirmaSenhaErro))
                .addGap(18, 18, 18)
                .addComponent(btnCriarConta)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfActionPerformed

    private void btnCriarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarContaActionPerformed
        boolean erro = false;
        String nome = txtNome.getText();
        String cpf = txtCpf.getText();
        String dataNascimento = txtNascimento.getText();
        String telefone = txtTelefone.getText();
        String login = txtLogin.getText();
        char[] senha = txtSenha.getPassword();
        char[] confirmaSenha = txtConfirmarSenha.getPassword();
        
        //Verifica se os campos estão vazios
        if( nome.isEmpty() ){
            Border border = BorderFactory.createLineBorder(Color.red, 2);
            txtNome.setBorder(border);
            txtNomeErro.setText("Nome não pode estar vazio!");
        }
        if( cpf.isEmpty() ){
            Border border = BorderFactory.createLineBorder(Color.red, 2);
            txtCpf.setBorder(border);
            txtCpfErro.setText("CPF não pode estar vazio!");
            erro = true;
        }
        if( dataNascimento.isEmpty() ){
            Border border = BorderFactory.createLineBorder(Color.red, 2);
            txtNascimento.setBorder(border);
            txtNascimentoErro.setText("<html>Data de Nascimento<br> não pode estar vazio!</html>");
            erro = true;
        }
        if( telefone.isEmpty() ){
            Border border = BorderFactory.createLineBorder(Color.red, 2);
            txtTelefone.setBorder(border);
            txtTelefoneErro.setText("Telefone não pode estar vazio!");
            erro = true;
        }
        if( login.isEmpty() ){
            Border border = BorderFactory.createLineBorder(Color.red, 2);
            txtLogin.setBorder(border);
            txtLoginErro.setText("Login não pode estar vazio!");
            erro = true;
        }
        if( senha.length == 0 ){
            Border border = BorderFactory.createLineBorder(Color.red, 2);
            txtSenha.setBorder(border);
            txtSenhaErro.setText("Senha não pode estar vazio!");
            erro = true;
        }
        if( confirmaSenha.length == 0){
            Border border = BorderFactory.createLineBorder(Color.red, 2);
            txtConfirmarSenha.setBorder(border);
            txtConfirmaSenhaErro.setText("Nome não pode estar vazio!");
            erro = true;
        }
        
        if( !(Arrays.equals(senha, confirmaSenha)) ){
            txtConfirmaSenhaErro.setText("Senha está diferente do confirma senha!");
            erro = true;
        }
        if(erro){
            return;
        }
        
        if(ValidadorUsuario.contemPalavraProibida(login)){
            JOptionPane.showMessageDialog(null, "Login contém palavra não permitida.", "ERRO!", 0);
            Border border = BorderFactory.createLineBorder(Color.red, 2);
            txtLogin.setBorder(border);
            txtLoginErro.setText("<html>Login contém palavra<br> não permitida.</html>");
            return;
        }
        
        //Armazenando no objeto Usuario.
        Usuario novoUsuario = new Usuario();
        novoUsuario.setNome(nome);
        novoUsuario.setCpf(cpf);
        novoUsuario.setGenero(String.valueOf(boxGenero.getSelectedItem()));
        novoUsuario.setDataNascimento(dataNascimento);
        novoUsuario.setTelefone(telefone);
        novoUsuario.setCargo(String.valueOf(boxCargo.getSelectedItem()));
        novoUsuario.setLogin(login);
        novoUsuario.setSenha(String.valueOf(senha));
        
        //manda a mensagem que deu certo e fecha a janela.
        JOptionPane.showMessageDialog(null, "Usuario " + novoUsuario.getNome() + " cadastrado com sucesso!");
        TelaCadastro.this.dispose();
    }//GEN-LAST:event_btnCriarContaActionPerformed

    private void boxGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxGeneroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaCadastro().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxCargo;
    private javax.swing.JComboBox<String> boxGenero;
    private javax.swing.JButton btnCriarConta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblConfirmarSenha;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblNascimento;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel txtConfirmaSenhaErro;
    private javax.swing.JPasswordField txtConfirmarSenha;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JLabel txtCpfErro;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JLabel txtLoginErro;
    private javax.swing.JTextField txtNascimento;
    private javax.swing.JLabel txtNascimentoErro;
    private javax.swing.JTextField txtNome;
    private javax.swing.JLabel txtNomeErro;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JLabel txtSenhaErro;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JLabel txtTelefoneErro;
    // End of variables declaration//GEN-END:variables
}
